### ISSUE TITLE
".hits.hits[]._id" nothing?why

### ISSUE THREAD

**Issue by hktalent** [simonnilsson/ask#1]
".hits.hits[]._id" nothing

".hits.hits[]" is ok
".hits.hits[0]._id" is ok

why?

**Comment by simonnilsson** [comment]
Hi

Since you didn't supply any definition of your data structure I will guess it looks something like this based on how you are trying to access it:
```json
{
  "hits": { 
    "hits": [{
      "_id": "ID"
    }]
  }
}
```

I think your primary confusion comes from the `[]` part of your path, brackets without any content will do nothing and it will be parsed like they don't even exist. So your examples will be parsed like this:

`".hits.hits[]._id"` > `"hits.hits._id"`
Since "hits" is a slice it does not have a _id field, this will not match.

`".hits.hits[]"` > `"hits.hits"`
This will point to the inner "hits" slice.

`".hits.hits[0]._id"` > `"hits.hits[0]._id"`
This will point to the value of "_id" at index 0 of "hits" slice, so "ID" in this example.

**Comment by hktalent** [comment]
You are right, it is indeed the case of arrays
<img width="682" alt="image" src="https://user-images.githubusercontent.com/18223385/175192621-45a1d1f9-d0cd-480f-98a2-b61da0cf6e9e.png">

I don't know if you can do 
".hits.hits[*]._id" 
thanks a lot
